ERROR: Exception:
Traceback (most recent call last):
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/shutil.py", line 816, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/n/home13/asaluja/.local/bin/convert-caffe2-to-onnx' -> '/tmp/pip-uninstall-smit0t7d/convert-caffe2-to-onnx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/site-packages/pip/_internal/commands/uninstall.py", line 103, in run
    uninstall_pathset = req.uninstall(
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 664, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/site-packages/pip/_internal/req/req_uninstall.py", line 373, in remove
    moved.stash(path)
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/site-packages/pip/_internal/req/req_uninstall.py", line 271, in stash
    renames(path, new_path)
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 312, in renames
    shutil.move(old, new)
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/n/home13/asaluja/.local/bin/convert-caffe2-to-onnx'
ERROR: Exception:
Traceback (most recent call last):
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 503, in run
    installed = install_given_reqs(
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/site-packages/pip/_internal/req/__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 796, in install
    install_wheel(
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 729, in install_wheel
    _install_wheel(
  File "/n/sw/Mambaforge-22.11.1-4/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 618, in _install_wheel
    assert os.path.exists(pyc_path)
AssertionError
Traceback (most recent call last):
  File "/n/home13/asaluja/Shrub2/Alexnet+Cifar10/alexnet_cifar10.py", line 4, in <module>
    from torchvision import datasets, transforms
ModuleNotFoundError: No module named 'torchvision'
